#! /bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <file>"
    exit 1
fi

file="$1"
repo="`dirname $(readlink $file)`"
echo "$repo"
cd "$repo"

msg="Updated $file"
if [[ $# -gt 1 ]]; then
    msg="$2"
fi

git commit -a -m "$msg"
